@baseUrl = http://localhost:5000
@urlPath = api/v1

###
PUT {{baseUrl}}/{{urlPath}}/user/follow/64b0dc0f5e7d8265cd760428
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
PUT {{baseUrl}}/{{urlPath}}/user/unfollow/64b0dc0f5e7d8265cd760428/64b242e100a94f5cb2fd8c7e
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
GET {{baseUrl}}/{{urlPath}}/user/following
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/user/followers/64b0dc0f5e7d8265cd760428
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/user/block/64b242e100a94f5cb2fd8c7e
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
PUT {{baseUrl}}/{{urlPath}}/user/unblock/64b242e100a94f5cb2fd8c7e
Content-Type: application/json
Accept: application/json
withCredentials: true

{}
