@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/notifications
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/notification/64b2862ad33f315e0fdc5ac7
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
DELETE {{baseUrl}}/{{urlPath}}/notification/64b2862ad33f315e0fdc5ac7
Content-Type: application/json
Accept: application/json
withCredentials: true

{}
